title: FrontPage 2.0
description: > # this means to ignore newlines until "baseurl:"
  Data Enthusiast, Pratical technophile. Ex Bloomberg.
permalink: ':title/'
baseurl: "/pages" # the subpath of your site, e.g. /blog
url: "https://jayteetk.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Justin Chen # add your name
author-img: justin-chen.jpg # add your photo
about-author: BI Analyst uncovering data driven solutions | TMT Research | CPA # add description
social-twitter: # add your Twitter handle
social-github: jayteetk # add your Github handle
social-linkedin: justinttk # add your Linkedin handle
social-email: justin.ttk@gmail.com # add your Email address

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
#analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
